services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./apps/server:/app/apps/server
      - /app/apps/server/node_modules
    environment:
      DATABASE_URL: 
      NODE_ENV: development
      PORT: 8080
      JWT_SECRET: secret
