import { ApolloWrapper } from "@/providers/apollo-provider";
import "@repo/ui/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {

  const cookieStore = cookies();
  const delay = Number(cookieStore.get("apollo-x-custom-delay")?.value ?? 1000);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper delay={delay}>
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
