/** @type {import('prettier').Config} */

module.exports = {
  printWidth: 80,
  tabWidth: 2,
  semi: true,
  useTabs: false,
  singleQuote: false,
  bracketSameLine: false,
  arrowParens: "always",
  trailingComma: "all",
  endOfLine: "lf",
  importOrder: [
    "<BUILT_IN_MODULES>",
    "",
    "modules",
    "",
    "^(react/(.*)$)|^(react$)",
    "",
    "^(next$)|^(next/(.*)$)",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@repo/ui/components/(.*)$",
    "",
    "^@repo/ui/lib/(.*)$",
    "",
    "^@/providers/(.*)$",
    "",
    "^@/components/(.*)$",
    "",
    "^@/config/(.*)$",
    "",
    "^@/hooks/(.*)$",
    "",
    "^@/lib/(.*)$",
    "",
    "^@/types/(.*)$",
    "",
    "^[.]",
  ],
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
};
